"""Generate the repository-local analyzer wrapper and state directories."""

from __future__ import annotations

import os
import stat
from dataclasses import dataclass
from pathlib import Path

CONFIG_TEMPLATE = """# Generated by connection-map init. Customize this file per repository.

[analysis]
language = \"python\"
# 複数言語のリポジトリでは language = \"mixed\" に変更し、languages に対象を列挙してください。
# 例: languages = [\"python\", \"html\", \"css\", \"javascript\", \"typescript\"]
# 対応言語をすべて解析する場合は language = \"all\" です。
# Web系だけの場合は language = \"web\" と languages = [\"html\", \"css\", \"javascript\", \"typescript\"] です。
# C/C++だけの場合は language = \"c-family\" と languages = [\"c\", \"cpp\"] です。
# mixedでC/C++を含める場合は languages に \"c\" と \"cpp\" を明示追加します。
# Javaだけの場合は language = \"java\" です。
# mixedでJavaを含める場合は languages に \"java\" を明示追加します。
# C#だけの場合は language = \"csharp\" です。
# mixedでC#を含める場合は languages に \"csharp\" を明示追加します。
# Goだけの場合は language = \"go\" です。
# mixedでGoを含める場合は languages に \"go\" を明示追加します。
# Rustだけの場合は language = \"rust\" です。
# mixedでRustを含める場合は languages に \"rust\" を明示追加します。
# PHPだけの場合は language = \"php\" です。
# mixedでPHPを含める場合は languages に \"php\" を明示追加します。
# Rubyだけの場合は language = \"ruby\" です。
# mixedでRubyを含める場合は languages に \"ruby\" を明示追加します。
# Kotlinだけの場合は language = \"kotlin\" です。
# mixedでKotlinを含める場合は languages に \"kotlin\" を明示追加します。
# Swiftだけの場合は language = \"swift\" です。
# v1.1の言語を複数選択する場合は language = \"mixed\" とし、languages に各言語のキー（例: \"lua\", \"hcl\"）を明示します。
# mixedでSwiftを含める場合は languages に \"swift\" を明示追加します。
include_tests = false
follow_symlinks = false
max_file_bytes = 2000000
include = [
  \"**/*.py\",
  \"**/*.html\",
  \"**/*.htm\",
  \"**/*.xhtml\",
  \"**/*.css\",
  \"**/*.js\",
  \"**/*.jsx\",
  \"**/*.mjs\",
  \"**/*.cjs\",
  \"**/*.ts\",
  \"**/*.mts\",
  \"**/*.cts\",
  \"**/*.tsx\",
  \"**/*.c\",
  \"**/*.cc\",
  \"**/*.cpp\",
  \"**/*.cxx\",
  \"**/*.c++\",
  \"**/*.h\",
  \"**/*.hh\",
  \"**/*.hpp\",
  \"**/*.hxx\",
  \"**/*.h++\",
  \"**/*.inc\",
  \"**/*.ipp\",
  \"**/*.inl\",
  \"**/*.java\",
  \"**/*.cs\",
  \"**/*.go\",
  \"**/*.rs\",
  \"**/*.php\",
  \"**/*.phtml\",
  \"**/*.rb\",
  \"**/*.rake\",
  \"**/*.gemspec\",
  \"**/*.ru\",
  \"**/*.kt\",
  \"**/*.kts\",
  \"**/*.swift\",
  \"**/*.sh\",
  \"**/*.bash\",
  \"**/*.bats\",
  \"**/*.command\",
  \"**/*.ps1\",
  \"**/*.psm1\",
  \"**/*.psd1\",
  \"**/*.dart\",
  \"**/*.scala\",
  \"**/*.sc\",
  \"**/*.sql\",
  \"**/*.pgsql\",
  \"**/*.psql\",
  \"**/*.tsql\",
  \"**/*.mysql.sql\",
  \"**/*.postgres.sql\",
  \"**/*.sqlite.sql\",
  \"**/*.sqlserver.sql\",
  \"**/*.oracle.sql\",
  \"**/*.vb\",
  \"**/*.vbhtml\",
  \"**/*.bas\",
  \"**/*.cls\",
  \"**/*.frm\",
  \"**/*.vba\",
  \"**/*.lua\",
  \"**/*.hs\",
  \"**/*.lhs\",
  \"**/*.pl\",
  \"**/*.pm\",
  \"**/*.t\",
  \"**/*.m\",
  \"**/*.mlx\",
  \"**/*.cob\",
  \"**/*.cbl\",
  \"**/*.cpy\",
  \"**/*.f\",
  \"**/*.for\",
  \"**/*.f77\",
  \"**/*.f90\",
  \"**/*.f95\",
  \"**/*.f03\",
  \"**/*.f08\",
  \"**/*.r\",
  \"**/*.rmd\",
  \"**/*.mm\",
  \"**/*.cu\",
  \"**/*.cuh\",
  \"**/*.groovy\",
  \"**/*.gradle\",
  \"**/*.gvy\",
  \"**/*.gy\",
  \"**/*.gsh\",
  \"**/*.fs\",
  \"**/*.fsi\",
  \"**/*.fsx\",
  \"**/*.fsscript\",
  \"**/*.asm\",
  \"**/*.s\",
  \"**/*.hcl\",
  \"**/*.tf\",
  \"**/*.tfvars\",
  \"**/*.gd\",
  \"**/*.ex\",
  \"**/*.exs\",
  \"**/*.zig\",
  \"**/*.jl\",
  \"**/*.pas\",
  \"**/*.pp\",
  \"**/*.p\",
  \"**/*.erl\",
  \"**/*.hrl\",
  \"**/*.escript\",
]
exclude = [
  \".git/**\",
  \".connection-map/**\",
  \"**/__pycache__/**\",
  \"**/.venv/**\",
  \"**/venv/**\",
  \"**/env/**\",
  \"**/build/**\",
  \"**/dist/**\",
  \"**/node_modules/**\",
  \"**/.next/**\",
  \"**/.cache/**\",
  \"**/target/**\",
  \"**/vendor/**\",
  \"**/.build/**\",
  \"**/DerivedData/**\",
  \"**/Pods/**\",
  \"**/Carthage/**\",
  \"**/SourcePackages/**\",
  \"**/coverage/**\",
]
test_patterns = [
  \"tests/**\",
  \"test/**\",
  \"**/test_*.py\",
  \"**/*_test.py\",
  \"**/test_*.c\",
  \"**/test_*.h\",
  \"**/test_*.cc\",
  \"**/test_*.cpp\",
  \"**/test_*.hpp\",
  \"**/test_*.cxx\",
  \"**/*_test.c\",
  \"**/*_test.h\",
  \"**/*_test.cc\",
  \"**/*_test.cpp\",
  \"**/*_test.hpp\",
  \"**/*_test.cxx\",
  \"**/*Test.java\",
  \"**/Test*.java\",
  \"**/*Tests.java\",
  \"**/*Test.cs\",
  \"**/Test*.cs\",
  \"**/*Tests.cs\",
  \"**/*_test.go\",
  \"**/*_test.rs\",
  \"**/*Test.php\",
  \"**/*TestCase.php\",
  \"**/*_test.php\",
  \"**/spec/**/*.rb\",
  \"**/*_spec.rb\",
  \"**/*_test.rb\",
  \"**/test_*.rb\",
  \"**/src/test/**/*.kt\",
  \"**/src/test/*.kt\",
  \"**/src/test/**/*.kts\",
  \"**/src/test/*.kts\",
  \"**/*Test.kt\",
  \"**/*Tests.kt\",
  \"**/*Test.kts\",
  \"**/*Tests.kts\",
  \"**/Tests/**/*.swift\",
  \"**/tests/**/*.swift\",
  \"**/test/**/*.swift\",
  \"**/*Test.swift\",
  \"**/*Tests.swift\",
  \"**/*TestSupport.swift\",
]
generated = [\"**/Generated/**\", \"**/generated/**\", \"**/__generated__/**\", \"**/*.g.cs\", \"**/*.designer.cs\", \"**/*.gen.go\", \"**/*.generated.rs\", \"**/*_generated.rs\", \"**/*.generated.php\", \"**/*_generated.php\", \"**/*.generated.rb\", \"**/*_generated.rb\", \"**/*.generated.kt\", \"**/*_generated.kt\", \"**/*.generated.kts\", \"**/*_generated.kts\", \"**/*.generated.swift\", \"**/*_generated.swift\", \"**/*+Generated.swift\", \"**/*Generated.swift\", \"**/*.generated.vb\", \"**/*_generated.vb\", \"**/*.designer.vb\", \"**/*.generated.bas\", \"**/*_generated.bas\", \"**/*.generated.dart\", \"**/*_generated.dart\", \"**/*.g.dart\", \"**/*.freezed.dart\", \"**/*.mocks.dart\", \"**/*bindings.dart\", \"**/*.generated.scala\", \"**/*_generated.scala\", \"**/*.generated.lua\", \"**/*_generated.lua\", \"**/*.generated.hs\", \"**/*_generated.hs\", \"**/*.generated.pl\", \"**/*_generated.pl\", \"**/*.generated.m\", \"**/*_generated.m\", \"**/*.generated.f90\", \"**/*_generated.f90\", \"**/*.generated.r\", \"**/*_generated.r\", \"**/*.generated.mm\", \"**/*_generated.mm\", \"**/*.generated.cu\", \"**/*_generated.cu\", \"**/*.generated.groovy\", \"**/*_generated.groovy\", \"**/*.generated.fs\", \"**/*_generated.fs\", \"**/*.generated.asm\", \"**/*_generated.asm\", \"**/*.generated.tf\", \"**/*_generated.tf\", \"**/*.generated.gd\", \"**/*_generated.gd\", \"**/*.generated.ex\", \"**/*_generated.ex\", \"**/*.generated.zig\", \"**/*_generated.zig\", \"**/*.generated.jl\", \"**/*_generated.jl\", \"**/*.generated.pas\", \"**/*_generated.pas\", \"**/*.generated.erl\", \"**/*_generated.erl\"]
"""


ANALYZER_README = """# Repository analyzer

このディレクトリは対象リポジトリ固有の解析入口です。共通実装は隣の `../core/` から読み込み、対象固有の設定は `../config.toml` に置きます。Core更新時も、このディレクトリは上書きしません。

## Webを含まない解析

Pythonだけを選択している場合は、対象側の通常のPython環境で実行できます。

```powershell
uv run python .connection-map/analyzer/run.py analyze `
  --root . --config .connection-map/config.toml
```

## Web・主要言語・追加言語・複数言語解析

Web、主要言語、Shell、追加言語、`mixed`、`all`でTree-sitter解析を使う場合は、対象側のwrapperを実行する環境へ`tree-sitter-language-pack`を追加します。SQL製品（`mysql`、`postgresql`、`sqlite`、`sqlserver`、`oracle`）には`sqlglot`が必要です。`all`は選択した全言語分の依存が必要です。対応する個別言語キーも直接指定できます。KotlinはJavaと同じJVM向け文法を使います。VB.NETの専用構文解析器はWindows x64で`tree-sitter-vbnet`を追加します。Linux、macOS、Windows ARM64では専用依存なしの正規表現フォールバックを使います。

```powershell
uv run --with tree-sitter-language-pack==1.14.3 `
  python .connection-map/analyzer/run.py analyze `
  --root . --config .connection-map/config.toml
```

SQLを含む場合:

```powershell
uv run --with tree-sitter-language-pack==1.14.3 `
  --with sqlglot==30.17.0 `
  python .connection-map/analyzer/run.py analyze `
  --root . --config .connection-map/config.toml
```

VB.NET専用構文解析器を使う場合（Windows x64）:

```powershell
uv run --with tree-sitter-language-pack==1.14.3 `
  --with tree-sitter-vbnet==0.1.0 `
  python .connection-map/analyzer/run.py analyze `
  --root . --config .connection-map/config.toml
```

解析後の `validate`、`split`、`serve` は次のように実行します。

```powershell
uv run python .connection-map/analyzer/run.py validate `
  .connection-map/snapshots/analysis.json
uv run python .connection-map/analyzer/run.py split `
  .connection-map/snapshots/analysis.json `
  --output .connection-map/snapshots/graph-bundle
uv run python .connection-map/analyzer/run.py serve `
  --input .connection-map/snapshots/analysis.json `
  --bundle .connection-map/snapshots/graph-bundle
```
"""


RUNNER = """from __future__ import annotations

import sys
from pathlib import Path


CORE_SRC = Path(__file__).resolve().parents[1] / \"core\" / \"src\"
if not CORE_SRC.is_dir():
    raise SystemExit(f\"core is not installed: {CORE_SRC}\")
sys.path.insert(0, str(CORE_SRC))

from connection_map.cli import main  # noqa: E402


if __name__ == \"__main__\":
    raise SystemExit(main())
"""


ROOT_README = """# Connection Analysis Mapping installation

このディレクトリは対象リポジトリ用の設定と利用者状態を保持します。共通実装の仕様は `core/docs/`、対象リポジトリの解析範囲は `config.toml` を参照してください。

## 構成

| パス | 役割 | 更新元 |
| --- | --- | --- |
| `core/` | 共通CLI、解析器、Web UI、仕様 | CoreのReleaseから更新 |
| `analyzer/` | 対象リポジトリ用の実行入口 | 対象リポジトリで管理 |
| `config.toml` | 解析言語、包含・除外範囲 | 対象リポジトリで管理 |
| `layout/` | 座標、カメラ、手動overlay | 利用者が必要に応じて管理 |
| `snapshots/` | 解析JSONと静的バンドル | 再生成対象。既定ではGit管理外 |
| `backups/` | core更新前のバックアップ | 更新時に自動生成。通常はGit管理外 |

## 初回導入・更新

インストーラーは `core/` の導入と初期雛形の作成に使います。次のコマンドはソースアーカイブを展開したディレクトリで実行します。更新時も `analyzer/`、`config.toml`、`layout/`、既存の解析結果を上書きせず、旧coreを `backups/` へ保存します。

```powershell
cd <source-directory>
uv run connection-map install-core --root <target-repository> --archive <release-source-archive>
uv run connection-map rollback-core --root <target-repository>
```

## 解析と表示

対応言語は個別キーで選択できます。`mixed`で指定した言語を一つの結果へ統合し、`all`ですべての対応言語を解析できます。`web`、`c-family`、`shell`、`sql` は関連する言語をまとめて選択するプリセットです。Tree-sitter解析時は `analyzer/README.md` の依存追加手順を確認してください。解析後は `serve` でローカル表示し、ブラウザの表示言語フィルターで対象を切り替えます。

## Git管理と機密情報

`core/`、`backups/`、`snapshots/`、`web/`は生成物のためGit管理外です。`config.toml`、`analyzer/`、`layout/`は対象リポジトリ固有の設定・拡張・レイアウトとして管理できます。`layout/`と`manual-v1.json`には注釈や外部ノードを保存できるため、公開前に絶対パス、ユーザー名、内部構造、外部サービス名を確認してください。解析結果をGit管理する場合だけ、`.gitignore`を明示的に変更してください。

## Core文書の参照先

- 導入・更新: `core/docs/installation.md`
- 操作: `core/docs/operation.md`
- コマンド: `core/docs/commands.md`
- 対応言語: `core/docs/languages.md`
"""


LAYOUT_README = """# Layout

ここには利用者が保存した座標・カメラ状態を置きます。解析結果とは別管理です。

推奨ファイル:

```text
layout-v1.json
```

Web UI の `レイアウトを保存` で生成したJSONを配置し、serve時に `--layout` で指定してください。

手動関係・外部ノード・注釈は、同じディレクトリの `manual-v1.json` に保存し、`connection-map merge` で解析結果へ適用します。layout と manual overlay は解析 snapshot と別管理です。
"""


MANUAL_TEMPLATE = """{
  "format": "connection-analysis-manual",
  "schema_version": "1.0",
  "analysis_schema_version": "1.0",
  "nodes": [],
  "edges": [],
  "annotations": []
}
"""


SNAPSHOT_GITIGNORE = "*\n!.gitignore\n"

LOCAL_MODE_GITIGNORE = "core/\nbackups/\nsnapshots/\nweb/\n"
FORCE_REFRESHABLE_FILES = frozenset(
    {
        Path("snapshots/.gitignore"),
        Path("web/.gitignore"),
        Path("backups/.gitignore"),
        Path("layout/.gitkeep"),
    }
)


@dataclass(frozen=True, slots=True)
class ScaffoldResult:
    created: tuple[Path, ...]
    skipped: tuple[Path, ...]


def _is_link_or_reparse_point(path: Path) -> bool:
    try:
        info = os.lstat(path)
    except FileNotFoundError:
        return False
    except OSError as exc:
        raise ValueError(f"cannot inspect scaffold path: {path}") from exc
    return stat.S_ISLNK(info.st_mode) or bool(getattr(info, "st_file_attributes", 0) & 0x400)


def initialize_target(
    root: Path,
    install_dir: str = ".connection-map",
    *,
    force: bool = False,
    force_all: bool = False,
) -> ScaffoldResult:
    """Create the scaffold, with an explicit boundary for destructive refreshes.

    ``force`` refreshes only generated control files.  ``force_all`` is the
    explicit destructive mode for replacing user-managed templates as well.
    """

    target_root = root.resolve()
    if not target_root.is_dir():
        raise ValueError(f"target repository directory does not exist: {target_root}")
    relative_install = Path(install_dir)
    if relative_install.is_absolute() or ".." in relative_install.parts:
        raise ValueError("install_dir must be a relative directory inside the target root")
    if not relative_install.parts:
        raise ValueError("install_dir must name a child directory inside the target root")
    raw_base = target_root / relative_install
    current = target_root
    for part in relative_install.parts:
        current /= part
        if _is_link_or_reparse_point(current):
            raise ValueError(f"install directory must not be a symlink or junction: {current}")
    base = raw_base.resolve()
    try:
        base.relative_to(target_root)
    except ValueError as exc:
        raise ValueError("install_dir resolves outside the target root") from exc
    if base.exists() and not base.is_dir():
        raise ValueError(f"install directory is not a directory: {base}")
    files = {
        base / ".gitignore": LOCAL_MODE_GITIGNORE,
        base / "README.md": ROOT_README,
        base / "config.toml": CONFIG_TEMPLATE,
        base / "analyzer" / "README.md": ANALYZER_README,
        base / "analyzer" / "__init__.py": "\"\"\"Repository-specific analyzer extensions.\"\"\"\n",
        base / "analyzer" / "run.py": RUNNER,
        base / "snapshots" / ".gitignore": SNAPSHOT_GITIGNORE,
        base / "web" / ".gitignore": SNAPSHOT_GITIGNORE,
        base / "backups" / ".gitignore": SNAPSHOT_GITIGNORE,
        base / "layout" / ".gitkeep": "",
        base / "layout" / "README.md": LAYOUT_README,
        base / "layout" / "manual-v1.json": MANUAL_TEMPLATE,
    }
    created: list[Path] = []
    skipped: list[Path] = []
    for path, content in files.items():
        # `force=True` must never turn a scaffold file into an arbitrary
        # write target through a pre-existing symlink or symlinked directory.
        current = base
        for part in path.relative_to(base).parts[:-1]:
            current /= part
            if _is_link_or_reparse_point(current):
                raise ValueError(f"scaffold path must not contain a symlink or junction: {current}")
        if _is_link_or_reparse_point(path):
            raise ValueError(f"scaffold path must not be a symlink or junction: {path}")
        resolved_path = path.resolve()
        try:
            resolved_path.relative_to(base)
        except ValueError as exc:
            raise ValueError(f"scaffold path resolves outside install directory: {path}") from exc
        relative = path.relative_to(base)
        if path.exists():
            if not force or (not force_all and relative not in FORCE_REFRESHABLE_FILES):
                skipped.append(path)
                continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        created.append(path)
    return ScaffoldResult(tuple(created), tuple(skipped))
